config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'comments/new'
  # get 'likes/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true, allow_blank: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    include JsonWebToken
    class UsersController < ApiController
      before_action :authorize_request, except: :login
      def index
        users = User.all
        render json: { status: 'SUCCESS', message: 'Loaded users successfully', data: users }, status: :ok
      end

      def login
        @user = User.find_by_email(params[:email])
        if @user
          token = jwt_encode(user_id: @user.id)
          time = Time.now + 7.days.to_i
          render json: { token:, exp: time.strftime('%m-%d-%Y %H:%M'),
                         Name: @user.name }, status: :ok
        else
          render json: { error: 'unauthorized' }, status: :unauthorized
        end
      end

      private

      def login_params
        params.permit(:email, :password)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<main>
  <section>
    <ul>
      <% @users.each do |user|%>
        <%= link_to user do %>
          <li class="card hover">
            <div class="user-image border"></div>
            <div class="user-data border">
              <h1><%= user.name %></h1>
              <p class="number-posts">Number of posts: <%= user.posts_counter %></p>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>  
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section>
    <div class="card">
      <div class="user-image border"></div>
      <div class="user-data border">
        <h1><%= @user.name %></h1>
        <p class="number-posts">Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
    <div class="card">
      <div class="column">
        <h3>Bio:</h3>
        <p><%= @user.bio %></p>
      </div>
    </div>
  </section>
  <section class="center">
    <ul>
      <% @user.recent_posts.each do |post| %>
        <%= link_to user_posts_path(@user) do %>
          <li class="card column hover">
            <h3 class="left"><%= post.title%></h3>
            <h4 class="left"><%= post.text%></h4>
            <div class="right">
              <span>Comments: <%= post.comments_counter %></span>
              <span class="left">Likes: <%= post.likes_counter %> </span>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
  </section> 
</main>